
      {/*
      Consent Lifecycle Section is intentionally commented until the backend API
      provides lifecycle timeline fields.

      <Card sx={{ boxShadow: 1 }}>
        <CardHeader
          title={
            <Typography variant="subtitle1" fontWeight={600}>
              {t('consentRegistry.details.section.lifecycle', 'Consent Lifecycle')}
            </Typography>
          }
          sx={{ pb: 0 }}
        />
        <Divider />
        <TableContainer>
          <Table sx={{ '& tbody tr:hover': { bgcolor: 'action.hover' } }}>
            <TableHead>
              <TableRow sx={{ bgcolor: 'action.default' }}>
                <TableCell sx={{ fontWeight: 700 }}>
                  {t('consentRegistry.details.table.eventType', 'Event Type')}
                </TableCell>
                <TableCell sx={{ fontWeight: 700 }}>
                  {t('consentRegistry.details.table.date', 'Date')}
                </TableCell>
                <TableCell sx={{ fontWeight: 700 }}>
                  {t('consentRegistry.details.table.time', 'Time')}
                </TableCell>
                <TableCell sx={{ fontWeight: 700 }}>
                  {t('consentRegistry.details.table.description', 'Description')}
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              <TableRow>
                <TableCell>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: 'action.disabled' }} />
                    <Typography variant="body2" fontWeight={600}>
                      Pending
                    </Typography>
                  </Stack>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">2026-03-01</Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">09:15:04</Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    Initial consent request generated by client application.
                  </Typography>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: 'success.main' }} />
                    <Typography variant="body2" fontWeight={600}>
                      Approved
                    </Typography>
                  </Stack>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">2026-03-02</Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">15:29:57</Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    Authorization confirmed by user through banking portal.
                  </Typography>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: 'primary.main' }} />
                    <Typography variant="body2" fontWeight={600}>
                      Active
                    </Typography>
                  </Stack>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">2026-03-02</Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">15:30:00</Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    Consent is now live and can be utilized for data sharing.
                  </Typography>
                </TableCell>
              </TableRow>
              <TableRow sx={{ opacity: 0.6 }}>
                <TableCell>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: 'action.disabled' }} />
                    <Typography variant="body2" fontWeight={600} color="text.secondary">
                      Expired
                    </Typography>
                  </Stack>
                </TableCell>
                <TableCell>
                  <Typography variant="body2" color="text.secondary">
                    2026-05-30
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2" color="text.secondary">
                    23:59:59
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2" color="text.secondary">
                    Scheduled expiry date based on 90-day duration policy.
                  </Typography>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </TableContainer>
      </Card>
      */}