// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentpurposemodel "github.com/wso2/openfgc/internal/consentpurpose/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wso2/openfgc/internal/system/database/model"
)

// ConsentPurposeStore is an autogenerated mock type for the ConsentPurposeStore type
type ConsentPurposeStore struct {
	mock.Mock
}

type ConsentPurposeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentPurposeStore) EXPECT() *ConsentPurposeStore_Expecter {
	return &ConsentPurposeStore_Expecter{mock: &_m.Mock}
}

// CheckPurposeNameExists provides a mock function with given fields: ctx, name, clientID, orgID, excludePurposeID
func (_m *ConsentPurposeStore) CheckPurposeNameExists(ctx context.Context, name string, clientID string, orgID string, excludePurposeID *string) (bool, error) {
	ret := _m.Called(ctx, name, clientID, orgID, excludePurposeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPurposeNameExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (bool, error)); ok {
		return rf(ctx, name, clientID, orgID, excludePurposeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) bool); ok {
		r0 = rf(ctx, name, clientID, orgID, excludePurposeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = rf(ctx, name, clientID, orgID, excludePurposeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_CheckPurposeNameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPurposeNameExists'
type ConsentPurposeStore_CheckPurposeNameExists_Call struct {
	*mock.Call
}

// CheckPurposeNameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - clientID string
//   - orgID string
//   - excludePurposeID *string
func (_e *ConsentPurposeStore_Expecter) CheckPurposeNameExists(ctx interface{}, name interface{}, clientID interface{}, orgID interface{}, excludePurposeID interface{}) *ConsentPurposeStore_CheckPurposeNameExists_Call {
	return &ConsentPurposeStore_CheckPurposeNameExists_Call{Call: _e.mock.On("CheckPurposeNameExists", ctx, name, clientID, orgID, excludePurposeID)}
}

func (_c *ConsentPurposeStore_CheckPurposeNameExists_Call) Run(run func(ctx context.Context, name string, clientID string, orgID string, excludePurposeID *string)) *ConsentPurposeStore_CheckPurposeNameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *ConsentPurposeStore_CheckPurposeNameExists_Call) Return(_a0 bool, _a1 error) *ConsentPurposeStore_CheckPurposeNameExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_CheckPurposeNameExists_Call) RunAndReturn(run func(context.Context, string, string, string, *string) (bool, error)) *ConsentPurposeStore_CheckPurposeNameExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePurpose provides a mock function with given fields: tx, purpose
func (_m *ConsentPurposeStore) CreatePurpose(tx model.TxInterface, purpose *consentpurposemodel.ConsentPurpose) error {
	ret := _m.Called(tx, purpose)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentpurposemodel.ConsentPurpose) error); ok {
		r0 = rf(tx, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentPurposeStore_CreatePurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePurpose'
type ConsentPurposeStore_CreatePurpose_Call struct {
	*mock.Call
}

// CreatePurpose is a helper method to define mock.On call
//   - tx model.TxInterface
//   - purpose *consentpurposemodel.ConsentPurpose
func (_e *ConsentPurposeStore_Expecter) CreatePurpose(tx interface{}, purpose interface{}) *ConsentPurposeStore_CreatePurpose_Call {
	return &ConsentPurposeStore_CreatePurpose_Call{Call: _e.mock.On("CreatePurpose", tx, purpose)}
}

func (_c *ConsentPurposeStore_CreatePurpose_Call) Run(run func(tx model.TxInterface, purpose *consentpurposemodel.ConsentPurpose)) *ConsentPurposeStore_CreatePurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentpurposemodel.ConsentPurpose))
	})
	return _c
}

func (_c *ConsentPurposeStore_CreatePurpose_Call) Return(_a0 error) *ConsentPurposeStore_CreatePurpose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentPurposeStore_CreatePurpose_Call) RunAndReturn(run func(model.TxInterface, *consentpurposemodel.ConsentPurpose) error) *ConsentPurposeStore_CreatePurpose_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePurpose provides a mock function with given fields: tx, purposeID, orgID
func (_m *ConsentPurposeStore) DeletePurpose(tx model.TxInterface, purposeID string, orgID string) error {
	ret := _m.Called(tx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentPurposeStore_DeletePurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePurpose'
type ConsentPurposeStore_DeletePurpose_Call struct {
	*mock.Call
}

// DeletePurpose is a helper method to define mock.On call
//   - tx model.TxInterface
//   - purposeID string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) DeletePurpose(tx interface{}, purposeID interface{}, orgID interface{}) *ConsentPurposeStore_DeletePurpose_Call {
	return &ConsentPurposeStore_DeletePurpose_Call{Call: _e.mock.On("DeletePurpose", tx, purposeID, orgID)}
}

func (_c *ConsentPurposeStore_DeletePurpose_Call) Run(run func(tx model.TxInterface, purposeID string, orgID string)) *ConsentPurposeStore_DeletePurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_DeletePurpose_Call) Return(_a0 error) *ConsentPurposeStore_DeletePurpose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentPurposeStore_DeletePurpose_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentPurposeStore_DeletePurpose_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePurposeElements provides a mock function with given fields: tx, purposeID, orgID
func (_m *ConsentPurposeStore) DeletePurposeElements(tx model.TxInterface, purposeID string, orgID string) error {
	ret := _m.Called(tx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposeElements")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentPurposeStore_DeletePurposeElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePurposeElements'
type ConsentPurposeStore_DeletePurposeElements_Call struct {
	*mock.Call
}

// DeletePurposeElements is a helper method to define mock.On call
//   - tx model.TxInterface
//   - purposeID string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) DeletePurposeElements(tx interface{}, purposeID interface{}, orgID interface{}) *ConsentPurposeStore_DeletePurposeElements_Call {
	return &ConsentPurposeStore_DeletePurposeElements_Call{Call: _e.mock.On("DeletePurposeElements", tx, purposeID, orgID)}
}

func (_c *ConsentPurposeStore_DeletePurposeElements_Call) Run(run func(tx model.TxInterface, purposeID string, orgID string)) *ConsentPurposeStore_DeletePurposeElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_DeletePurposeElements_Call) Return(_a0 error) *ConsentPurposeStore_DeletePurposeElements_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentPurposeStore_DeletePurposeElements_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentPurposeStore_DeletePurposeElements_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposeByID provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) GetPurposeByID(ctx context.Context, purposeID string, orgID string) (*consentpurposemodel.ConsentPurpose, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeByID")
	}

	var r0 *consentpurposemodel.ConsentPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentpurposemodel.ConsentPurpose, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentpurposemodel.ConsentPurpose); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_GetPurposeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposeByID'
type ConsentPurposeStore_GetPurposeByID_Call struct {
	*mock.Call
}

// GetPurposeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeID string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) GetPurposeByID(ctx interface{}, purposeID interface{}, orgID interface{}) *ConsentPurposeStore_GetPurposeByID_Call {
	return &ConsentPurposeStore_GetPurposeByID_Call{Call: _e.mock.On("GetPurposeByID", ctx, purposeID, orgID)}
}

func (_c *ConsentPurposeStore_GetPurposeByID_Call) Run(run func(ctx context.Context, purposeID string, orgID string)) *ConsentPurposeStore_GetPurposeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeByID_Call) Return(_a0 *consentpurposemodel.ConsentPurpose, _a1 error) *ConsentPurposeStore_GetPurposeByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeByID_Call) RunAndReturn(run func(context.Context, string, string) (*consentpurposemodel.ConsentPurpose, error)) *ConsentPurposeStore_GetPurposeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposeByName provides a mock function with given fields: ctx, name, orgID
func (_m *ConsentPurposeStore) GetPurposeByName(ctx context.Context, name string, orgID string) (*consentpurposemodel.ConsentPurpose, error) {
	ret := _m.Called(ctx, name, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeByName")
	}

	var r0 *consentpurposemodel.ConsentPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentpurposemodel.ConsentPurpose, error)); ok {
		return rf(ctx, name, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentpurposemodel.ConsentPurpose); ok {
		r0 = rf(ctx, name, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_GetPurposeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposeByName'
type ConsentPurposeStore_GetPurposeByName_Call struct {
	*mock.Call
}

// GetPurposeByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) GetPurposeByName(ctx interface{}, name interface{}, orgID interface{}) *ConsentPurposeStore_GetPurposeByName_Call {
	return &ConsentPurposeStore_GetPurposeByName_Call{Call: _e.mock.On("GetPurposeByName", ctx, name, orgID)}
}

func (_c *ConsentPurposeStore_GetPurposeByName_Call) Run(run func(ctx context.Context, name string, orgID string)) *ConsentPurposeStore_GetPurposeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeByName_Call) Return(_a0 *consentpurposemodel.ConsentPurpose, _a1 error) *ConsentPurposeStore_GetPurposeByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeByName_Call) RunAndReturn(run func(context.Context, string, string) (*consentpurposemodel.ConsentPurpose, error)) *ConsentPurposeStore_GetPurposeByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposeElements provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) GetPurposeElements(ctx context.Context, purposeID string, orgID string) ([]consentpurposemodel.PurposeElement, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeElements")
	}

	var r0 []consentpurposemodel.PurposeElement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentpurposemodel.PurposeElement, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentpurposemodel.PurposeElement); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.PurposeElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_GetPurposeElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposeElements'
type ConsentPurposeStore_GetPurposeElements_Call struct {
	*mock.Call
}

// GetPurposeElements is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeID string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) GetPurposeElements(ctx interface{}, purposeID interface{}, orgID interface{}) *ConsentPurposeStore_GetPurposeElements_Call {
	return &ConsentPurposeStore_GetPurposeElements_Call{Call: _e.mock.On("GetPurposeElements", ctx, purposeID, orgID)}
}

func (_c *ConsentPurposeStore_GetPurposeElements_Call) Run(run func(ctx context.Context, purposeID string, orgID string)) *ConsentPurposeStore_GetPurposeElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeElements_Call) Return(_a0 []consentpurposemodel.PurposeElement, _a1 error) *ConsentPurposeStore_GetPurposeElements_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeElements_Call) RunAndReturn(run func(context.Context, string, string) ([]consentpurposemodel.PurposeElement, error)) *ConsentPurposeStore_GetPurposeElements_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposeIDByName provides a mock function with given fields: ctx, purposeName, orgID
func (_m *ConsentPurposeStore) GetPurposeIDByName(ctx context.Context, purposeName string, orgID string) (string, error) {
	ret := _m.Called(ctx, purposeName, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeIDByName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, purposeName, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, purposeName, orgID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeName, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_GetPurposeIDByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposeIDByName'
type ConsentPurposeStore_GetPurposeIDByName_Call struct {
	*mock.Call
}

// GetPurposeIDByName is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeName string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) GetPurposeIDByName(ctx interface{}, purposeName interface{}, orgID interface{}) *ConsentPurposeStore_GetPurposeIDByName_Call {
	return &ConsentPurposeStore_GetPurposeIDByName_Call{Call: _e.mock.On("GetPurposeIDByName", ctx, purposeName, orgID)}
}

func (_c *ConsentPurposeStore_GetPurposeIDByName_Call) Run(run func(ctx context.Context, purposeName string, orgID string)) *ConsentPurposeStore_GetPurposeIDByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeIDByName_Call) Return(_a0 string, _a1 error) *ConsentPurposeStore_GetPurposeIDByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_GetPurposeIDByName_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *ConsentPurposeStore_GetPurposeIDByName_Call {
	_c.Call.Return(run)
	return _c
}

// IsElementUsedInPurposes provides a mock function with given fields: ctx, elementID, orgID
func (_m *ConsentPurposeStore) IsElementUsedInPurposes(ctx context.Context, elementID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for IsElementUsedInPurposes")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_IsElementUsedInPurposes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsElementUsedInPurposes'
type ConsentPurposeStore_IsElementUsedInPurposes_Call struct {
	*mock.Call
}

// IsElementUsedInPurposes is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) IsElementUsedInPurposes(ctx interface{}, elementID interface{}, orgID interface{}) *ConsentPurposeStore_IsElementUsedInPurposes_Call {
	return &ConsentPurposeStore_IsElementUsedInPurposes_Call{Call: _e.mock.On("IsElementUsedInPurposes", ctx, elementID, orgID)}
}

func (_c *ConsentPurposeStore_IsElementUsedInPurposes_Call) Run(run func(ctx context.Context, elementID string, orgID string)) *ConsentPurposeStore_IsElementUsedInPurposes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_IsElementUsedInPurposes_Call) Return(_a0 bool, _a1 error) *ConsentPurposeStore_IsElementUsedInPurposes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_IsElementUsedInPurposes_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ConsentPurposeStore_IsElementUsedInPurposes_Call {
	_c.Call.Return(run)
	return _c
}

// LinkElementToPurpose provides a mock function with given fields: tx, purposeID, elementID, orgID, isMandatory
func (_m *ConsentPurposeStore) LinkElementToPurpose(tx model.TxInterface, purposeID string, elementID string, orgID string, isMandatory bool) error {
	ret := _m.Called(tx, purposeID, elementID, orgID, isMandatory)

	if len(ret) == 0 {
		panic("no return value specified for LinkElementToPurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string, bool) error); ok {
		r0 = rf(tx, purposeID, elementID, orgID, isMandatory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentPurposeStore_LinkElementToPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkElementToPurpose'
type ConsentPurposeStore_LinkElementToPurpose_Call struct {
	*mock.Call
}

// LinkElementToPurpose is a helper method to define mock.On call
//   - tx model.TxInterface
//   - purposeID string
//   - elementID string
//   - orgID string
//   - isMandatory bool
func (_e *ConsentPurposeStore_Expecter) LinkElementToPurpose(tx interface{}, purposeID interface{}, elementID interface{}, orgID interface{}, isMandatory interface{}) *ConsentPurposeStore_LinkElementToPurpose_Call {
	return &ConsentPurposeStore_LinkElementToPurpose_Call{Call: _e.mock.On("LinkElementToPurpose", tx, purposeID, elementID, orgID, isMandatory)}
}

func (_c *ConsentPurposeStore_LinkElementToPurpose_Call) Run(run func(tx model.TxInterface, purposeID string, elementID string, orgID string, isMandatory bool)) *ConsentPurposeStore_LinkElementToPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *ConsentPurposeStore_LinkElementToPurpose_Call) Return(_a0 error) *ConsentPurposeStore_LinkElementToPurpose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentPurposeStore_LinkElementToPurpose_Call) RunAndReturn(run func(model.TxInterface, string, string, string, bool) error) *ConsentPurposeStore_LinkElementToPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// ListPurposes provides a mock function with given fields: ctx, orgID, name, clientIDs, purposeNames, offset, limit
func (_m *ConsentPurposeStore) ListPurposes(ctx context.Context, orgID string, name string, clientIDs []string, purposeNames []string, offset int, limit int) ([]consentpurposemodel.ConsentPurpose, int, error) {
	ret := _m.Called(ctx, orgID, name, clientIDs, purposeNames, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPurposes")
	}

	var r0 []consentpurposemodel.ConsentPurpose
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, []string, int, int) ([]consentpurposemodel.ConsentPurpose, int, error)); ok {
		return rf(ctx, orgID, name, clientIDs, purposeNames, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, []string, int, int) []consentpurposemodel.ConsentPurpose); ok {
		r0 = rf(ctx, orgID, name, clientIDs, purposeNames, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string, []string, int, int) int); ok {
		r1 = rf(ctx, orgID, name, clientIDs, purposeNames, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, []string, []string, int, int) error); ok {
		r2 = rf(ctx, orgID, name, clientIDs, purposeNames, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsentPurposeStore_ListPurposes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPurposes'
type ConsentPurposeStore_ListPurposes_Call struct {
	*mock.Call
}

// ListPurposes is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - name string
//   - clientIDs []string
//   - purposeNames []string
//   - offset int
//   - limit int
func (_e *ConsentPurposeStore_Expecter) ListPurposes(ctx interface{}, orgID interface{}, name interface{}, clientIDs interface{}, purposeNames interface{}, offset interface{}, limit interface{}) *ConsentPurposeStore_ListPurposes_Call {
	return &ConsentPurposeStore_ListPurposes_Call{Call: _e.mock.On("ListPurposes", ctx, orgID, name, clientIDs, purposeNames, offset, limit)}
}

func (_c *ConsentPurposeStore_ListPurposes_Call) Run(run func(ctx context.Context, orgID string, name string, clientIDs []string, purposeNames []string, offset int, limit int)) *ConsentPurposeStore_ListPurposes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string), args[4].([]string), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *ConsentPurposeStore_ListPurposes_Call) Return(_a0 []consentpurposemodel.ConsentPurpose, _a1 int, _a2 error) *ConsentPurposeStore_ListPurposes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsentPurposeStore_ListPurposes_Call) RunAndReturn(run func(context.Context, string, string, []string, []string, int, int) ([]consentpurposemodel.ConsentPurpose, int, error)) *ConsentPurposeStore_ListPurposes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePurpose provides a mock function with given fields: tx, purpose
func (_m *ConsentPurposeStore) UpdatePurpose(tx model.TxInterface, purpose *consentpurposemodel.ConsentPurpose) error {
	ret := _m.Called(tx, purpose)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentpurposemodel.ConsentPurpose) error); ok {
		r0 = rf(tx, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentPurposeStore_UpdatePurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePurpose'
type ConsentPurposeStore_UpdatePurpose_Call struct {
	*mock.Call
}

// UpdatePurpose is a helper method to define mock.On call
//   - tx model.TxInterface
//   - purpose *consentpurposemodel.ConsentPurpose
func (_e *ConsentPurposeStore_Expecter) UpdatePurpose(tx interface{}, purpose interface{}) *ConsentPurposeStore_UpdatePurpose_Call {
	return &ConsentPurposeStore_UpdatePurpose_Call{Call: _e.mock.On("UpdatePurpose", tx, purpose)}
}

func (_c *ConsentPurposeStore_UpdatePurpose_Call) Run(run func(tx model.TxInterface, purpose *consentpurposemodel.ConsentPurpose)) *ConsentPurposeStore_UpdatePurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentpurposemodel.ConsentPurpose))
	})
	return _c
}

func (_c *ConsentPurposeStore_UpdatePurpose_Call) Return(_a0 error) *ConsentPurposeStore_UpdatePurpose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentPurposeStore_UpdatePurpose_Call) RunAndReturn(run func(model.TxInterface, *consentpurposemodel.ConsentPurpose) error) *ConsentPurposeStore_UpdatePurpose_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePurposeNames provides a mock function with given fields: ctx, purposeNames, orgID
func (_m *ConsentPurposeStore) ValidatePurposeNames(ctx context.Context, purposeNames []string, orgID string) (map[string]string, error) {
	ret := _m.Called(ctx, purposeNames, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePurposeNames")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (map[string]string, error)); ok {
		return rf(ctx, purposeNames, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) map[string]string); ok {
		r0 = rf(ctx, purposeNames, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, purposeNames, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentPurposeStore_ValidatePurposeNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePurposeNames'
type ConsentPurposeStore_ValidatePurposeNames_Call struct {
	*mock.Call
}

// ValidatePurposeNames is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeNames []string
//   - orgID string
func (_e *ConsentPurposeStore_Expecter) ValidatePurposeNames(ctx interface{}, purposeNames interface{}, orgID interface{}) *ConsentPurposeStore_ValidatePurposeNames_Call {
	return &ConsentPurposeStore_ValidatePurposeNames_Call{Call: _e.mock.On("ValidatePurposeNames", ctx, purposeNames, orgID)}
}

func (_c *ConsentPurposeStore_ValidatePurposeNames_Call) Run(run func(ctx context.Context, purposeNames []string, orgID string)) *ConsentPurposeStore_ValidatePurposeNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *ConsentPurposeStore_ValidatePurposeNames_Call) Return(_a0 map[string]string, _a1 error) *ConsentPurposeStore_ValidatePurposeNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentPurposeStore_ValidatePurposeNames_Call) RunAndReturn(run func(context.Context, []string, string) (map[string]string, error)) *ConsentPurposeStore_ValidatePurposeNames_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentPurposeStore creates a new instance of ConsentPurposeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentPurposeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentPurposeStore {
	mock := &ConsentPurposeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
